uapi-group/specifications

website/config.toml
website/content/_index.md

Set the base URL of the specs repo website to use uapi-group/specifications, and fix a link on the index page to the discoverable partitions spec.

website: base URL uapi-group.org, fix spec link

---

specs/unified_kernel_image.md

I think the `.pcrpkey` section should contain the public key, while the `.pcrsig` section should contain the signature (rather than the other way around).

UKI: fix typo

---

website/config.toml

Current links to edit pages on Github have an extra `/specs` in the URL.

website: fix 'Edit this page' links

---

specs/boot_loader_specification.md
specs/version_format_specification.md

This will be used for comparing DDIs too, so move it out of the BLS into its own document and reference it.

specs: move version specification from BLS to its own document

---

specs/linux_tpm_pcr_registry.md

This is mostly taken from systemd-cryptenroll(8) and slightly modernized.

specs: add more text about PCR usage

---

specs/unified_kernel_image.md

We were discussing in mkosi how to handle distribution-supplied UKIs in the future. It would be helpful to have a common location that producers can put them in and consumers can look for them. 
I'm open to a different location or naming scheme, the point is rather that there is a standard. 
I didn't touch on the UKI being installed to the ESP or XBOOTLDR directly (in Debian land dpkg can't even do that) - it would be possible within the *should* though -, but I think the general way would be for the package manager to put the UKI in the standard location and kernel-install or a tool like it, to marry it to local configuration (e.g. number of tries for boot counting) and putting it where it should go (ESP or XBOOTLDR).

UKI: define a location for centrally built UKIs

---

specs/version_format_specification.md

Commit cb3f5aaed58145aeeeaec0645577b721e1eb029f fixed the examples for tilde comparisons, but when comparing strings iteratively, the empty string will compare smaller than tilde at step 2, since the string consisting only of a tilde has a remaining character, while the empty string has none.
This change is consistent with the implementation in strverscmp_improved behind "systemd-analyze compare-versions", which first drops invalid characters, then handles tilde characters and afterwards checks if one of the strings has reached the end.

Remove step 2 from version format spec

---

specs/version_format_specification.md

Looking at the reference implementation in `systemd-analyze compare-versions` the code handling the caret character is the same as for `-` and `.`, right before and after:
```C
/* Handle '-', which separates version and release, e.g 123.4-3.1.fc33.x86_64 */
if (*a == '-' || *b == '-') {
/* The string prefixed with '-' is older (e.g., 123-9 vs 123.1-1) */
r = CMP(*a != '-', *b != '-');
if (r != 0)
return r;
a++;
b++;
}
/* Handle '^'. Used for patched release. */
if (*a == '^' || *b == '^') {
r = CMP(*a != '^', *b != '^');
if (r != 0)
return r;
a++;
b++;
}
/* Handle '.'. Used for point releases. */
if (*a == '.' || *b == '.') {
r = CMP(*a != '.', *b != '.');
if (r != 0)
return r;
a++;
b++;
}
```
so the caret character must be treated the same in the spec as well. This is not a bug in the …

Caret comparison

---

specs/boot_loader_specification.md

The current wording sometimes gets misinterpreted as having to search for /loader/entries on all filesystems in the partition table so let's clarify that /loader/entries should be located on the root of the ESP filesystem.

Clarify that /loader/entries should be in the root of the ESP filesystem

---

specs/unified_kernel_image.md

The .cmdline section in a UKI is optional in both sd-stub and ukify, so mark it as such in the specification too

specs: mark .cmdline in UKI as optional

---

specs/extension_image.md

sd-sysext uses versioned ordering, while ExtensionImages= respects the specified order

extensions: define ordering as implementation dependent

---

specs/unified_kernel_image.md

In connection with the discussion in [1] this pull request specifies how the case of multiple Device Trees is to be handled by choosing to append all additional Device Trees in the same .dtb section.
[1]: https://github.com/uapi-group/specifications/issues/66

UKI: document the case of multiple Device Trees

---

specs/boot_loader_specification.md

Fixes https://github.com/uapi-group/specifications/issues/63.
Quoting https://github.com/uapi-group/specifications/issues/63#issuecomment-1747361084:
> The portable links stuff was introduced in 4cd8de0, which also converted the
> relative links to their current form. Using relref[0] might be the easier way
> out here.
>
> [0] https://gohugo.io/content-management/cross-references/

specs/bls: fix relative links

---

specs/discoverable_partitions_specification.md

MIPS comes in little as well as big endianess, which is determined at system boot and usually cannot be changed after startup. Binutils and GCC use the arch prefix `mips` for the big-endian variant and `mipsel` for the little-endian variant, so use the same here.

specs: DPS: add GUIDs for big-endian MIPS architecture

---

specs/unified_kernel_image.md

That's what sd-stub also says.

UKI: say that .pcrsig section is not measured

---

specs/unified_kernel_image.md

This documents the `.ucode` section implemented in https://github.com/systemd/systemd/pull/31872, see there for most details.
It is relatively straightforward, just an initrd that is guaranteed to be handed to the kernel first.

uki: Add .ucode section

---

specs/configuration_files_specification.md

Also drop the sentence that "drop-ins are not full replacements" — in practice they are and I'm not sure what this sentence was trying to achieve.
Resolves #48.

specs/config-files: say that drop-ins are not always required

---

specs/version_format_specification.md

The previous version was unclear about whether upper- vs. lower-case comparisons are done in ASCII or merely to disambiguate, i.e. whether A<a<B<b or A<B<…<a<b.
This change makes this case more explicit and changes the example accordingly.

Disambiguate version_format_specification.md

---

specs/boot_loader_specification.md

The UKI description mentioned that it includes initrd and kernel command line resources and refers to the external systemd-stub reference for details. However, as described in the internal UKI reference, those are optional. This change reformulates the text such that it is made clear that UKIs should include an EFI stub loader and a kernel image and can include other, optional resources. Furthermore, the internal UKI reference is linked instead of the external systemd-stub reference.

Improve UKI description in boot_loader_specification.md

---

specs/unified_kernel_image.md

According with
https://github.com/systemd/systemd/issues/29372#issuecomment-1843130973

UKI: document where UKI addons provided via package should be

---

specs/extension_image.md

This PR extends the extension specification (covering confext and sysext) by optional mutability modes for extensions.
Specifically, it discusses 3 modes:
1. Immutable. This is the default and the way extensions are currently defined.
2. Mutable with a persistent backing directory ("upperdir"). This allows changed to the filesystem's base directories even after extensions are overlaid.
3. Ephemeral. Base directories are mutable, but changes go to ephemeral storage like tmpfs.
A total of 3 configuration options are discussed for setting up mutable modes for base directories.
Please refer to the diff included in this PR for the changes, and /or to the full document at https://github.com/flatcar/uapi-group-specifications/blob/main/specs/extension_image.md .
Prior discussions here: …

specs/extension_image: Add optional mutability for extensions

---

specs/unified_kernel_image.md

Corresponding systemd PR: https://github.com/systemd/systemd/pull/34680

Add initrd addons to the UKI spec

---

specs/file_hierarchy_for_the_verification_of_os_artifacts.md

Define a common scheme for cryptographic validation of OS artifacts. Specify a stateless directory hierarchy for the use with various cryptographic technologies, such as OpenPGP and X.509. Provide examples for the use of VOA based on verification with and without trust anchors.
Fixes: https://github.com/uapi-group/specifications/issues/115
cc @xsuchy @dkg @santiagotorres

File Hierarchy for the Verification of OS Artifacts (VOA)

---

specs/linux_file_system_hierarchy.md

/opt/ is used by software such as Chrome or Signal, and it's also supported by specifications like sysexts, so add a paragraph defining it.

LFSH: add paragraph for /opt/

---

specs/boot_loader_specification.md

This is used by https://github.com/systemd/systemd/pull/36314 to make networking boot work nicely within the BLS constructs.
The "uki" stanza also should have uses in a world where a single UKI shall be invoked by multiple locally defined menu entries, for example on nixos or ostree systems, where each commit shall synthesize a separate menu entry, often referencing the same UKI.

bls: introduce "uki" and "uki-url" keys to the BLS spec
